### PR TITLE
Fix catching user's initial config state

### PR DESCRIPTION
**Pull request by afterlook**
Hint state was taken out one layer upwards to main interfaces in order to fix hop pattern as it adds virtual cursor which corrupts user settings. Because of that, hint state has to be saved before that happens.

This is a direct follow up to #148. This rewrite should solve this issue entirely for all cases.

### CODE REVIEW

**Review by jakub-jaskulski — APPROVED** [review]

**Comment by smoka7** [comment]
I can't reproduce this on https://github.com/smoka7/hop.nvim/commit/88516dde51b0b603ce43739220150f7b66a6841c. Can you provide a minimal reproduction? There is an issue template in the repo you can use it.
The fix you're suggesting is a breaking change to hop api, we have to find another solution.

**Comment by afterlook** [comment]
How to reproduce:
1. `set cursorline` for current vim session
2. execute `HopPattern`
3. Finish jumping to found pattern
4. cursorline gets unset.

I'll try to figure out later how to do this without breaking the API. For my needs, I don't really care about this, but I totally get your point. Wasn't thinking about this at all when I was hacking to get `cursorline` working.

**Comment by smoka7** [comment]
Okay, I reproduced it. 
Highlighting has changed since this https://github.com/phaazon/hop.nvim/pull/148 (see the screenshot).
2023-09-11T14:52:17,918098291+03:30
And the issue which the original pr addressed is resolved now. I think its better to remove the toggling of cursorline.

**Comment by afterlook** [comment]
Okayyy that is nice, in a couple of hours I'll see if everything is okay if `cursorline` stuff is removed completely from `state` and `quit` or any other part of the code.

Then I'll probably close this pr myself and open new one with issue attached properly. Thanks!

**Comment by smoka7** [comment]
> Then I'll probably close this pr myself and open new one with issue attached properly. Thanks!
There is no need no bother yourself with a new pr, push here and at the end I'll squash and merge.

**Comment by smoka7** [comment]
Delete the `.luarc.json` and it's done. Thanks for the work :+1::+1:.

**Comment by afterlook** [comment]
Overlooked... Done

**Pull request merged**
